### ISSUE TITLE
about Repo Public

### ISSUE THREAD

**Issue by pmh-only** [seoaapp/Filtering#1]
이제 이 레포 열어도 되지 않을까요?

**Comment by DPS0340** [comment]
토큰 때문에...

**Comment by pmh-only** [comment]
음 그러면 환경변수를 써보는건 어떠신가요

**Comment by DPS0340** [comment]
커밋 내역에 토큰이 이미 남아서 리보크하지않는한 퍼블릭으로 돌리기는 힘들다는의미였습니다

**Comment by DPS0340** [comment]
물론 리보크하고 gitignore를 쓰거나 dbms를 쓰면 가능하겠죠

**Comment by hwahyang1** [comment]
공개용 레포를 따로 만드는게 낫지 않을까요

**Comment by ttakkku** [comment]
@DPS0340  그렇게 하는 게 좋을 거 같네요

**Comment by pmh-only** [comment]
@DPS0340 저도 revoke하자는 생각이였습니다

**Comment by DPS0340** [comment]
제 토큰은 일단 다시 생성하고 숨겼어요

**Comment by DPS0340** [comment]
.gitignore로 로컬에서만 토큰이 있게...

**Comment by pmh-only** [comment]
그러면 @ttakkku 레포 공개로 전환해 주세요

**Comment by DPS0340** [comment]
https://github.com/ttakkku/Filtering/blob/master/python/hynus/filterbot.py
hynus님 토큰 리보크된거 확실한가요?

**Comment by pmh-only** [comment]
아 hynus님도 계시는구나

**Comment by hwahyang1** [comment]
저분 셤기간이라 못쓰실껄요 컴

**Comment by pmh-only** [comment]
이미 처리된 내용이니 닫도록 하겠습니다
